### ISSUE TITLE
Error - Unable to set default language!

### ISSUE THREAD

**Issue by Wiethoofd** [dozius/winsplit-revolution#2]
On launch of the 10.0.0.0 release on Windows 10 Pro x64 1909 I get an error popup on start:

> Unable to set default language!

It does not matter if I launch it normally or as administrator (required to make key binds work), change language to not be English, but the program launches anyway in the configured language.

**Comment by dozius** [comment]
This seems to be an issue with loading the operating system language. What language is set in your OS?

**Comment by dozius** [comment]
More specifically, it's trying to load the default locale used by the OS. This may be different than the UI language you have set in the OS.

[wxLocale::Init](https://docs.wxwidgets.org/trunk/classwx_locale.html#a37c254f20d4862b6efea2fedf63a231a)

**Comment by Wiethoofd** [comment]
English (United States), but with English (Netherlands) as _Default app language_
![image](https://user-images.githubusercontent.com/9917564/78465562-6fa05680-76f7-11ea-9d43-6a5eee843a88.png)

**Comment by dozius** [comment]
Thanks. I can confirm that wxWidgets doesn't support the English (Netherlands) locale which is most likely why you get that message. I think the best I can do is to fail silently and fall back to English. From what I can tell it already does this anyways, so the warning is more of a nuisance than anything else.

Not sure when I will have time to fix this, but I will try to get to it next weekend. In the meantime, it's safe to just ignore it.

**Comment by gittmin** [comment]
THE FIX IS HERE!  -- You guys are going to love this solution! :D 🙋🙆🙋✋	 

I got a fix for you and it will work with just about any kind of popup problem.

1. Download Dexpot

![image](https://user-images.githubusercontent.com/97714787/233505931-541e0397-7359-4d36-a601-a1721f83a3b2.png)


3. After installing, look for it's blue square icon in your hidden taskbar area. Clue. If it's not visible look under the arrow's hidden area. Clue: press WIN+B to jump to it then "ENTER" 

4. Right click on the little blue icon when found.

![image](https://user-images.githubusercontent.com/97714787/233505889-f701020b-cfbf-4d6a-adc9-d74ddf57b6fc.png)

![image](https://user-images.githubusercontent.com/97714787/233505773-8cb29d12-5df9-462b-81e1-f6897d8bf022.png)

5. Click Desktop Rules

![image](https://user-images.githubusercontent.com/97714787/233505747-43e775cd-2e68-4220-a282-e1b887c02232.png)


![image](https://user-images.githubusercontent.com/97714787/233505708-9b0195c2-9f73-4697-87c7-253d004949c3.png)

6. Click Assistant

![image](https://user-images.githubusercontent.com/97714787/233506002-5f4690d2-60a0-4133-aeb6-379610a7d0c5.png)

7. Name the new rule -- any name will do.

8. Click the little White Square that looks like a mini window with a circle or bullseye in it. But when you click don't let go. Click then drag to where the annoying popup is.

9. I normally like to click add and then apply this not only to the title but the class and Executable. See below:

10. Make sure to click the "Match all conditions" option and not the "match any" option otherwise it might trigger the wrong window.
![image](https://user-images.githubusercontent.com/97714787/233506411-5f510d87-27c6-4965-bfb8-9ee1e9dff199.png)

11. Don't let this one confuse you. But it's for reference after I applied three different commands to ensure I get the right popup window and not accidentally another window.  One condition should be enough but I"m paranoid so I add three to avoid future bugs.

![image](https://user-images.githubusercontent.com/97714787/233506090-a01d3629-21dd-4008-a4f6-507800efb80e.png)

12. Last don't forget to set an action: I set it to close the window, but if that doesn't work, you can have it set to minimize it to the tray or simply minimize.
![image](https://user-images.githubusercontent.com/97714787/233506654-8e05a221-f8cf-4bbb-b130-964cc8258f11.png)

     
Cheers!
As I'm not on here much. Feel free to look me up if you need more help.

Brother Brandon
You can find me on jesusdramatized. com as this is where I am most of the time.

I hope all this helps you

**Comment by dozius** [comment]
@gittmin this issue was resolved over three years ago. Please don't spam it with irrelevant comments.
