### ISSUE TITLE
Launch as Administrator required to move Admin elevated windows

### ISSUE THREAD

**Issue by Wiethoofd** [dozius/winsplit-revolution#4]
I'm using HWMonitor to keep an eye on temperatures/fan speeds occasionally, which requires to be launched as Administrator to access those sensors.

Moving this window to resize it with my keybinds or the popup won't work unless Winsplit is also launched as Administrator.

I assume this is intended Windows 10 behaviour, or would it be possible to not launch as admin and still move those admin elevated type of windows?

**Comment by dozius** [comment]
Yes, this is just the way the Windows security model works. Specifically, User Interface Privilege Isolation. Details [here](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/user-account-control-allow-uiaccess-applications-to-prompt-for-elevation-without-using-the-secure-desktop).

There is a way to bypass it but it requires a very specific set of criteria, one of which is to have the application digitally signed. Since certificates cost money, I likely won't ever implement this unless someone donates a certificate.

Alternatively, people can make their own builds using self-signed certificates for personal use.
